server {
    listen 80;
    server_name _;

    root /var/www/fittrack;
    index index.html;

    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;

    location / {
        try_files $uri /index.html;
    }

    location /api/users/        { proxy_pass http://192.168.100.3:8002/users/; }
    location /api/measurements/ { proxy_pass http://192.168.100.3:8001/; }
    location /api/progress/     { proxy_pass http://192.168.100.3:8005/progress/; }
    location /api/goals/        { proxy_pass http://192.168.100.3:8004/goals/; }
    location /api/workouts/     { proxy_pass http://192.168.100.3:8003/api/routines/; }
}
